version: '3.0'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development
    ports:
      - "5432:5432"