version: '3.0'
services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    command: npm run start:dev
    networks:
      - dwa
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    networks:
      - dwa

networks:
  dwa:
volumes:
  pgdata: